baseURL = "higueronforsale.com"
disqusShortname = ""
googleAnalytics = "UA-189981792-2"
paginate = "3"
summaryLength = "15"
theme = "Higueron"
title = "Higueron | For Sale"
[markup.goldmark.renderer]
unsafe = true
