[de]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "De"
title = "Bigspring Hugo"
weight = 2
[en]
contentDir = "content/english"
copyright = "[HigueronForSale.com](https://higueronforsale.com/) Copyright 2021. Costa del Sol New Developments"
footer_content = "Lomas del Higueron is the best New Development in Costa del Sol. Great setting, impressive features and the best views. "
footer_menu_left = "Company"
footer_menu_middle = "Project"
footer_menu_right = "Support"
languageName = "English"
title = "Higueron For Sale"
weight = 1
