[[footer_left]]
name = "Contact Us"
url = "contact"
[[footer_left]]
name = "Go Home"
url = "#"
[[footer_left]]
name = "More info"
url = "contact"
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Plans"
url = "https://higueronforsale.com/blog/post-6/"
[[footer_middle]]
name = "Renders"
url = "https://higueronforsale.com/blog/post-3/"
[[footer_right]]
name = "Contact"
url = "contact"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Project"
url = "blog"
weight = 2
[[main]]
name = "Pricing"
url = "pricing"
weight = 3
[[main]]
name = "Contact"
url = "contact"
weight = 4
